# This is a basic workflow to help you get started with Actions

name: AppScan on Cloud SAST workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "scan"
  Scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Check Python Version
        run: |
          python3 --version
        shell: bash
      # Check working directory
      - name: Show Working Directory
        run: |
          pwd
        shell: bash
      # Runs list files in the current working dir
      - name: List Directory
        run: |
          ls -la
        shell: bash
      
      # Runs AppScan Step
      - name: Perform HCL AppScan Security Analysis
        env:
          ASOC_KEY: ${{ secrets.ASOC_API_KEY }}
          ASOC_SECRET: ${{ secrets.ASOC_API_SECRET }}
          ASOC_SCAN_NAME: Automated Scan from Github Actions
          ASOC_APPID: 4813c695-d1aa-4c70-9455-e2705869e8f6

        run: |
          echo "AppScan on Cloud Step Here"
          env
        shell: bash
          
